info:
  contact: {}
paths:
  /login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":,"",data:""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /problem_detail:
    get:
      parameters:
      - description: problem identity
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":,"",data:""}'
          schema:
            type: string
      summary: 问题详情
      tags:
      - 公共方法
  /problem_list:
    get:
      parameters:
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: 分类的唯一标识
        in: query
        name: category_identity
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":,"",data:""}'
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
  /submit_list:
    get:
      parameters:
      - description: problem_identity
        in: query
        name: problem_identity
        type: string
      - description: 请输入当前页,默认第一页
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: user_identity
        in: query
        name: user_identity
        type: string
      - description: status
        in: query
        name: status
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":,"",data:""}'
          schema:
            type: string
      summary: 提交列表
      tags:
      - 公共方法
  /user_detail:
    get:
      parameters:
      - description: user identity
        in: query
        name: identity
        type: string
      responses:
        "200":
          description: '{"code":"200","msg":,"",data:""}'
          schema:
            type: string
      summary: 用户详情
      tags:
      - 公共方法
swagger: "2.0"
