info:
  contact: {}
paths:
  /problem_list:
    get:
      parameters:
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: 请输入当前页,默认第二页
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      responses:
        "200":
          description: '{"code":"200","msg":,"",data:""}'
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
swagger: "2.0"
